### ISSUE TITLE
This project doesn't currently build on Node v8.5.0

### ISSUE THREAD

**Issue by matthew-dean** [codemix/htmling-demo-app#1]
It seems there may be a dependency issue with fsevents.

```
CXX(target) Release/obj.target/fse/fsevents.o
In file included from ../fsevents.cc:6:
../../nan/nan.h:339:13: error: no member named 'New' in 'v8::String'
    return  _NAN_ERROR(v8::Exception::Error, errmsg);
```
...plus other related errors.
